name: metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.11.0
  - pip:
    - biopython==1.79
    - jupyterlab==3.6.1
    - sourmash==4.7.0
    - jsonapi-client==0.9.9
    - pandas==1.3.4
    - requests==2.28.2
    - matplotlib==3.7.1
    - sphinx==6.1.3